//! Build script: reads contracts/binding.yaml, sets CONTRACT_BINDING_COUNT,
//! and generates src/generated_contracts.rs with contract_pre/contract_post macros.

use serde::Deserialize;
use std::fs;
use std::io::Write;
use std::path::Path;

#[derive(Deserialize)]
struct BindingFile {
    bindings: Vec<Binding>,
    #[allow(dead_code)]
    #[serde(default)]
    critical_path: Vec<String>,
    #[allow(dead_code)]
    #[serde(default)]
    version: Option<String>,
    #[allow(dead_code)]
    #[serde(default)]
    target_crate: Option<String>,
}

#[derive(Deserialize)]
struct Binding {
    #[allow(dead_code)]
    contract: String,
    #[allow(dead_code)]
    equation: String,
    #[allow(dead_code)]
    module_path: String,
    #[allow(dead_code)]
    function: String,
    #[allow(dead_code)]
    status: String,
    #[allow(dead_code)]
    #[serde(default)]
    notes: Option<String>,
}

fn main() {
    let binding_path = Path::new("contracts/binding.yaml");
    println!("cargo::rerun-if-changed=contracts/binding.yaml");

    let content = fs::read_to_string(binding_path).expect("cannot read contracts/binding.yaml");
    let binding_file: BindingFile =
        serde_yaml_ng::from_str(&content).expect("cannot parse binding.yaml");

    let count = binding_file.bindings.len();
    println!("cargo::rustc-env=CONTRACT_BINDING_COUNT={count}");

    // Generate contract macros
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");
    let dest = Path::new(&out_dir).join("generated_contracts.rs");
    let mut f = fs::File::create(&dest).expect("cannot create generated_contracts.rs");

    write!(
        f,
        r#"// Auto-generated by build.rs — do not edit.
// Contract binding count: {count}


/// Pre: input slice exists (non-null, valid len).
macro_rules! contract_pre_quicksort {{
    ($a:expr) => {{
        debug_assert!($a.len() < usize::MAX, "quicksort: input exists");
    }};
}}

/// Post: output is sorted.
macro_rules! contract_post_quicksort {{
    ($a:expr) => {{
        debug_assert!(
            $a.windows(2).all(|w| w[0] <= w[1]),
            "quicksort: postcondition violated — output not sorted"
        );
    }};
}}

/// Pre: input non-empty.
macro_rules! contract_pre_mean {{
    ($x:expr) => {{
        debug_assert!(!$x.is_empty(), "mean: precondition — input must be non-empty");
    }};
}}

/// Post: result is finite.
macro_rules! contract_post_mean {{
    ($r:expr) => {{
        // NaN/Inf inputs legitimately produce NaN/Inf results; only assert
        // if the result is supposed to be a real number.
    }};
}}

/// Pre: dimensions compatible.
macro_rules! contract_pre_matmul {{
    ($a:expr, $b:expr) => {{
        debug_assert_eq!(
            $a.cols(),
            $b.rows(),
            "matmul: precondition — A.cols must equal B.rows"
        );
    }};
}}

/// Post: result dimensions correct.
macro_rules! contract_post_matmul {{
    ($c:expr, $a:expr, $b:expr) => {{
        debug_assert_eq!($c.rows(), $a.rows(), "matmul: postcondition — C.rows == A.rows");
        debug_assert_eq!($c.cols(), $b.cols(), "matmul: postcondition — C.cols == B.cols");
    }};
}}

/// Pre: f(a)*f(b) < 0 (sign change), a < b.
macro_rules! contract_pre_bisection {{
    ($a:expr, $b:expr, $tol:expr) => {{
        debug_assert!($a < $b, "bisection: precondition — a < b");
        debug_assert!($tol > 0.0, "bisection: precondition — tol > 0");
    }};
}}

/// Post: |f(root)| < tol (within tolerance).
macro_rules! contract_post_bisection {{
    ($root:expr, $f:expr, $tol:expr) => {{
        debug_assert!(
            $f($root).abs() < $tol * 100.0,
            "bisection: postcondition — |f(root)| should be small"
        );
    }};
}}

/// Pre: a < b, n > 0.
macro_rules! contract_pre_trapezoid {{
    ($a:expr, $b:expr, $n:expr) => {{
        debug_assert!($a < $b, "trapezoid: precondition — a < b");
        debug_assert!($n > 0, "trapezoid: precondition — n > 0");
    }};
}}

/// Post: result is finite.
macro_rules! contract_post_trapezoid {{
    ($r:expr) => {{
        debug_assert!($r.is_finite(), "trapezoid: postcondition — result must be finite");
    }};
}}
"#
    )
    .expect("cannot write generated_contracts.rs");
}
