//! Golden vector tests: Python nlib output == Rust nlib output.
//!
//! Fixtures generated by `python3` from Di Pierro's formulas.
//! Any mismatch means Python and Rust implementations diverge.

fn load_vectors() -> serde_json::Value {
    let data = include_str!("fixtures/golden_vectors.json");
    serde_json::from_str(data).expect("golden_vectors.json must parse")
}

fn approx(a: f64, b: f64, tol: f64) -> bool {
    (a - b).abs() < tol
}

// =========================================================================
// Sort
// =========================================================================

#[test]
fn golden_sort() {
    let v = load_vectors();
    let input: Vec<i64> = serde_json::from_value(v["sort"]["input"].clone()).unwrap();
    let expected: Vec<i64> = serde_json::from_value(v["sort"]["quicksort"].clone()).unwrap();

    let mut q = input.clone();
    nlib::sort::quicksort(&mut q);
    assert_eq!(q, expected, "quicksort mismatch with Python");

    let m = nlib::sort::mergesort(&input);
    assert_eq!(m, expected, "mergesort mismatch with Python");

    let mut h = input.clone();
    nlib::sort::heapsort(&mut h);
    assert_eq!(h, expected, "heapsort mismatch with Python");
}

// =========================================================================
// Stats
// =========================================================================

#[test]
fn golden_stats_mean_variance() {
    let v = load_vectors();
    let x: Vec<f64> = serde_json::from_value(v["stats"]["x"].clone()).unwrap();
    let py_mean: f64 = v["stats"]["mean"].as_f64().unwrap();
    let py_var: f64 = v["stats"]["variance"].as_f64().unwrap();

    assert!(
        approx(nlib::stats::mean(&x), py_mean, 1e-12),
        "mean diverges from Python"
    );
    assert!(
        approx(nlib::stats::variance(&x), py_var, 1e-12),
        "variance diverges from Python"
    );
}

#[test]
fn golden_stats_correlation() {
    let v = load_vectors();
    let a: Vec<f64> = serde_json::from_value(v["stats"]["a"].clone()).unwrap();
    let b: Vec<f64> = serde_json::from_value(v["stats"]["b"].clone()).unwrap();
    let py_cov: f64 = v["stats"]["covariance"].as_f64().unwrap();
    let py_corr: f64 = v["stats"]["correlation"].as_f64().unwrap();

    assert!(
        approx(nlib::stats::covariance(&a, &b), py_cov, 1e-12),
        "covariance diverges"
    );
    assert!(
        approx(nlib::stats::correlation(&a, &b), py_corr, 1e-12),
        "correlation diverges"
    );
}

#[test]
fn golden_stats_chi_squared() {
    let v = load_vectors();
    let obs: Vec<f64> = serde_json::from_value(v["stats"]["observed"].clone()).unwrap();
    let exp: Vec<f64> = serde_json::from_value(v["stats"]["expected"].clone()).unwrap();
    let py_chi2: f64 = v["stats"]["chi_squared"].as_f64().unwrap();

    assert!(
        approx(nlib::stats::chi_squared(&obs, &exp), py_chi2, 1e-12),
        "chi2 diverges"
    );
}

// =========================================================================
// Solve
// =========================================================================

#[test]
fn golden_solve_bisection() {
    let v = load_vectors();
    let py_root: f64 = v["solve"]["bisection"]["expected"].as_f64().unwrap();

    let root = nlib::solve::bisection(|x| x * x - 2.0, 1.0, 2.0, 1e-14);
    assert!(
        approx(root, py_root, 1e-10),
        "bisection sqrt(2) diverges: {root} vs {py_root}"
    );
}

#[test]
fn golden_solve_fixed_point() {
    let v = load_vectors();
    let py_fp: f64 = v["solve"]["fixed_point"]["expected"].as_f64().unwrap();

    let fp = nlib::solve::fixed_point(|x| x.cos(), 1.0, 1e-14);
    assert!(
        approx(fp, py_fp, 1e-10),
        "fixed_point cos(x)=x diverges: {fp} vs {py_fp}"
    );
}

// =========================================================================
// Integrate
// =========================================================================

#[test]
fn golden_integrate_simpson_x2() {
    let v = load_vectors();
    let py_val: f64 = v["integrate"]["simpson_x2_0_1_50"]["expected"]
        .as_f64()
        .unwrap();

    let result = nlib::integrate::simpson(|x| x * x, 0.0, 1.0, 50);
    assert!(
        approx(result, py_val, 1e-10),
        "simpson x^2 diverges: {result} vs {py_val}"
    );
}

// =========================================================================
// Fourier
// =========================================================================

#[test]
fn golden_fourier_impulse() {
    let v = load_vectors();
    let py_out: Vec<Vec<f64>> =
        serde_json::from_value(v["fourier"]["dft_impulse"]["output"].clone()).unwrap();

    let input = vec![(1.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0)];
    let result = nlib::fourier::dft(&input);

    for (k, (re, im)) in result.iter().enumerate() {
        assert!(
            approx(*re, py_out[k][0], 1e-10),
            "DFT impulse re[{k}] diverges"
        );
        assert!(
            approx(*im, py_out[k][1], 1e-10),
            "DFT impulse im[{k}] diverges"
        );
    }
}

#[test]
fn golden_fourier_dc() {
    let v = load_vectors();
    let py_dc: f64 = v["fourier"]["dft_dc"]["output_0_re"].as_f64().unwrap();

    let input = vec![(3.0, 0.0); 4];
    let result = nlib::fourier::dft(&input);
    assert!(
        approx(result[0].0, py_dc, 1e-10),
        "DFT DC component diverges"
    );
}

// =========================================================================
// Matrix
// =========================================================================

#[test]
fn golden_matrix_determinant() {
    let v = load_vectors();
    let py_det: f64 = v["matrix"]["determinant"].as_f64().unwrap();

    let a = nlib::matrix::Matrix::from_rows(&[&[1.0, 2.0], &[3.0, 4.0]]);
    assert!(
        approx(nlib::matrix::determinant(&a), py_det, 1e-10),
        "det diverges"
    );
}

#[test]
fn golden_matrix_matmul() {
    let v = load_vectors();
    let py_c: Vec<Vec<f64>> =
        serde_json::from_value(v["matrix"]["matmul_AB"]["C"].clone()).unwrap();
    let expected: Vec<f64> = py_c.into_iter().flatten().collect();

    let a = nlib::matrix::Matrix::from_rows(&[&[1.0, 2.0], &[3.0, 4.0]]);
    let b = nlib::matrix::Matrix::from_rows(&[&[5.0, 6.0], &[7.0, 8.0]]);
    let c = nlib::matrix::matmul(&a, &b);

    for (i, (&rust_val, &py_val)) in c.data().iter().zip(expected.iter()).enumerate() {
        assert!(
            approx(rust_val, py_val, 1e-10),
            "matmul[{i}] diverges: {rust_val} vs {py_val}"
        );
    }
}

#[test]
fn golden_matrix_cholesky() {
    let v = load_vectors();
    let py_l: Vec<Vec<f64>> = serde_json::from_value(v["matrix"]["cholesky_L"].clone()).unwrap();
    let expected: Vec<f64> = py_l.into_iter().flatten().collect();

    let a = nlib::matrix::Matrix::from_rows(&[&[4.0, 2.0], &[2.0, 3.0]]);
    let l = nlib::matrix::cholesky(&a).expect("positive definite");

    for (i, (&rust_val, &py_val)) in l.data().iter().zip(expected.iter()).enumerate() {
        assert!(
            approx(rust_val, py_val, 1e-10),
            "cholesky[{i}] diverges: {rust_val} vs {py_val}"
        );
    }
}

// =========================================================================
// Graph
// =========================================================================

#[test]
fn golden_graph_dijkstra() {
    let v = load_vectors();
    let edges: Vec<Vec<f64>> =
        serde_json::from_value(v["graph"]["dijkstra_from_0"]["edges"].clone()).unwrap();
    let py_dist: Vec<f64> =
        serde_json::from_value(v["graph"]["dijkstra_from_0"]["distances"].clone()).unwrap();

    let mut g = nlib::graph::Graph::new(6);
    for e in &edges {
        g.add_undirected_edge(e[0] as usize, e[1] as usize, e[2]);
    }

    let dist = nlib::graph::dijkstra(&g, 0);
    for (i, (&rust_d, &py_d)) in dist.iter().zip(py_dist.iter()).enumerate() {
        assert!(
            approx(rust_d, py_d, 1e-10),
            "dijkstra[{i}] diverges: {rust_d} vs {py_d}"
        );
    }
}

// =========================================================================
// Random (LCG is deterministic — exact match required)
// =========================================================================

#[test]
fn golden_random_lcg() {
    let v = load_vectors();
    let py_vals: Vec<u64> =
        serde_json::from_value(v["random"]["lcg_minstd_seed1_first5"].clone()).unwrap();

    let mut lcg = nlib::random::Lcg::new(1, 16807, 0, 2_147_483_647);
    for (i, &py_val) in py_vals.iter().enumerate() {
        let rust_val = lcg.next_val();
        assert_eq!(
            rust_val, py_val,
            "LCG[{i}] diverges: {rust_val} vs {py_val}"
        );
    }
}
