#!/usr/bin/env bash
# readme_sync.sh — README.md is GENERATED, every byte of it; nobody edits it by hand (ONT-001 v4.17,
# ONT-G step "readme"; GH-1).
#
# README.md is a header line, then docs/README.md.in with the lines BETWEEN each marker pair filled:
#
#     <!-- ENFORCEMENT_START -->      ...   <!-- ENFORCEMENT_END -->
#     <!-- CONTRACT_TABLE_START -->   ...   <!-- CONTRACT_TABLE_END -->
#     <!-- SHACL_SUMMARY_START -->    ...   <!-- SHACL_SUMMARY_END -->
#     <!-- PROOF_STATUS_START -->     ...   <!-- PROOF_STATUS_END -->
#     <!-- EXAMPLE_TABLE_START -->    ...   <!-- EXAMPLE_TABLE_END -->
#     <!-- CONTRACT_METRICS_START --> ...   <!-- CONTRACT_METRICS_END -->
#
# Every number comes from one instrument:
#   - per-contract grades and the codebase grade: `pv score --format json`
#   - equations per contract: the keys of each contract's `equations:` block
#   - shapes, focus nodes, controls, bindings: `pv lint --gate shapes --format json`
#   - proof levels and counts: contracts/proof-status.json, the committed
#     `pv proof-status --verify-bindings --format json` receipt (the gate's regen step writes it)
#   - each example's Python original: contracts/example-origins.tsv at the ref pinned in
#     contracts/external-corpora.yaml; shape and proof-status anchors are looked up line by line
#   - Kani harnesses: `#[kani::proof]` in src/kani_harnesses.rs
#
# "What is enforced, and what is not" is ontology data. contracts/enforcement-claims.src.json holds
# one entity per claim (mechanism, red trigger, whether it blocks the merge, plant run, limit) with
# {{NAME}} where a measured count goes; this script substitutes the counts, writes the result to
# evidence/enforcement/claims.json, checks each claim's job against scripts/ci_gate.sh, and renders
# the table from it. contracts/enforcement-claims-v1.yaml closes those entities with a SHACL shape.
#
# Modes:
#   --write  write evidence/enforcement/claims.json and README.md (idempotent)
#   --print  print both; write nothing
#   --check  exit 0 iff both already equal what --write produces, byte for byte, else 1
#   --self-test  plant each claim fault in a scratch copy; every one must be caught
#
# A template without every marker pair is exit 3, never a silent no-op. A measure
# that reads empty or zero is a failure (ONT R-2: zero is a decline).

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
README="${README_PATH:-"$REPO_ROOT/README.md"}"
PV="${PV:-pv}"
PROOF=contracts/proof-status.json
TEMPLATE="${README_TEMPLATE:-"$REPO_ROOT/docs/README.md.in"}"
CLAIMS_SRC="${CLAIMS_SRC:-"$REPO_ROOT/contracts/enforcement-claims.src.json"}"
CLAIMS="${CLAIMS_PATH:-"$REPO_ROOT/evidence/enforcement/claims.json"}"
GENERATED_HEADER='<!-- GENERATED by scripts/readme_sync.sh from docs/README.md.in, contracts/ and evidence/. Do not edit: the contracts gate fails on any byte that differs from the regenerated file. -->'

die() {
    printf 'FAIL readme_sync: %s\n' "$1" >&2
    exit "${2:-1}"
}

usage() {
    printf 'usage: bash scripts/readme_sync.sh [--write|--print|--check|--self-test]\n' >&2
    exit 2
}

# The names of a contract's equations: two-space keys under `equations:`.
equations_of() {
    awk '/^equations:/ { on = 1; next }
         /^[^ #]/      { on = 0 }
         on && /^  [A-Za-z0-9_]+:/ { sub(/^  /, ""); sub(/:.*/, ""); printf "%s%s", sep, $0; sep = ", " }' "$1"
}

nonzero() { # nonzero <name> <value>
    case "$2" in
        '' | *[!0-9]*) die "$1 read '$2', not a number" ;;
    esac
    [ "$2" -gt 0 ] || die "$1 is 0: a broken measurement, not a README to regenerate"
}

measure() {
    cd "$REPO_ROOT" || exit 3
    local tmp
    tmp="$(mktemp -d)"
    trap 'rm -rf "${tmp:?}"' EXIT
    "$PV" score contracts/ --binding contracts/binding.yaml --format json >"$tmp/score.raw" 2>/dev/null \
        || die "pv score failed"
    jq -s '.' "$tmp/score.raw" >"$tmp/score.json" || die "pv score printed no JSON"
    "$PV" lint contracts/ --gate shapes --format json >"$tmp/shapes.json" 2>/dev/null \
        || die "pv lint --gate shapes did not pass"

    N_CONTRACTS=$(jq -r '.[0].contracts' "$tmp/score.json")
    MEAN=$(jq -r '.[0].mean_score * 100 | round / 100' "$tmp/score.json")
    MEAN_GRADE=$(jq -r '.[0].mean_grade' "$tmp/score.json")
    CB_GRADE=$(jq -r '.[1].codebase.grade' "$tmp/score.json")
    CB_SCORE=$(jq -r '.[1].codebase.composite * 100 | round / 100' "$tmp/score.json")
    SHAPES=$(jq -r '.shapes_n' "$tmp/shapes.json")
    FOCUS=$(jq -r '.focus_nodes_n' "$tmp/shapes.json")
    RESOLVED=$(jq -r '.symbols_resolved' "$tmp/shapes.json")
    UNRESOLVED=$(jq -r '.symbols_unresolved' "$tmp/shapes.json")
    PLANT_V=$(jq -r '.plant_violations' "$tmp/shapes.json")
    PC_SHAPE=$(jq -r '.pc_shape' "$tmp/shapes.json")
    PC_FIRED=$(jq -r '[.pc_extract[] | select(. == "fired")] | length' "$tmp/shapes.json")
    PC_N=$(jq -r '.pc_extract | length' "$tmp/shapes.json")
    W3C=$(jq -r '.w3c_cases_passed' "$tmp/shapes.json")
    W3C_N=$(jq -r '.w3c_cases_n' "$tmp/shapes.json")
    TRIPLES=$(jq -r '.triples' "$tmp/shapes.json")
    [ "$PC_SHAPE" = fired ] || die "pv's planted shape control did not fire ($PC_SHAPE)"
    [ "$PC_FIRED" = "$PC_N" ] || die "$PC_FIRED of $PC_N extractor controls fired"
    nonzero "planted violations" "$PLANT_V"
    nonzero "extractor controls" "$PC_N"
    nonzero "W3C cases" "$W3C"
    nonzero triples "$TRIPLES"
    KANI=$(grep -cF '#[kani::proof]' src/kani_harnesses.rs || true)
    nonzero contracts "$N_CONTRACTS"
    nonzero shapes "$SHAPES"
    nonzero "focus nodes" "$FOCUS"
    nonzero "resolved symbols" "$RESOLVED"
    nonzero "Kani harnesses" "$KANI"

    TABLE="$tmp/table.md"
    N_EQ=0
    {
        printf '| Contract | Grade | Spec | Falsify | Kani | Bind | Equations |\n'
        printf '|----------|-------|------|---------|------|------|-----------|\n'
        local stem cf eqs n
        while IFS=$'\t' read -r stem grade score spec fals kani bind; do
            cf="contracts/${stem}.yaml"
            eqs=$(equations_of "$cf")
            if [[ -n "$eqs" ]]; then
                n=$(printf '%s' "$eqs" | awk -F', ' '{ print NF }')
            elif grep -qxF '  kind: schema' "$cf"; then
                eqs='none (a schema contract: SHACL-closed data; its obligations are tested by `scripts/readme_sync.sh --self-test`)'
                n=0
            else
                die "$cf has no equations"
            fi
            N_EQ=$((N_EQ + n))
            printf '| %s | %s (%s) | %s | %s | %s | %s | %s |\n' \
                "$stem" "$grade" "$score" "$spec" "$fals" "$kani" "$bind" "$eqs"
        done < <(jq -r '.[0].scores | sort_by(.stem)[] |
            [.stem, .grade] + ([.composite, .spec_depth, .falsification_coverage, .kani_coverage, .binding_coverage]
            | map(. * 100 | round / 100 | if . == 0 then 0 else . end)) | @tsv' "$tmp/score.json")
    } >"$TABLE"
    nonzero equations "$N_EQ"
    TABLE_TEXT="$(cat "$TABLE")"
    rm -rf "${tmp:?}"
    trap - EXIT
    measure_examples
    measure_proofs
    measure_enforcement
}

# The per-example table (GH-1 scope b, c): links in the order rust, python, contract, shape, proof
# status. Every link target is looked up here, and a lookup that finds nothing is a failure; the
# gate's readme step then verifies each target independently (scripts/example_links.sh).
measure_examples() {
    local origins=contracts/example-origins.tsv
    local ref ex file sym line what stem shape_l proof_l level rows=""
    [ -f "$PROOF" ] || die "$PROOF is missing; the gate's regen step writes it"
    [ -f "$origins" ] || die "$origins is missing"
    ref=$(sed -n 's/^[[:space:]]*ref:[[:space:]]*\([0-9a-f]\{40\}\).*/\1/p' contracts/external-corpora.yaml | head -1)
    [ -n "$ref" ] || die "contracts/external-corpora.yaml pins no 40-hex ref"
    N_EX=0
    while IFS=$'\t' read -r ex file sym line _ what; do
        stem="example-${ex//_/-}-v1"
        [ -f "examples/$ex.rs" ] || die "$origins names $ex, but examples/$ex.rs does not exist"
        [ -f "contracts/$stem.yaml" ] || die "contracts/$stem.yaml does not exist"
        shape_l=$(grep -nF "shape/$stem> a sh:NodeShape" contracts/shapes.ttl | cut -d: -f1)
        [ "$(printf '%s' "$shape_l" | grep -c .)" = 1 ] || die "contracts/shapes.ttl declares no single shape for $stem"
        proof_l=$(grep -nF "\"stem\": \"$stem\"" "$PROOF" | cut -d: -f1)
        [ "$(printf '%s' "$proof_l" | grep -c .)" = 1 ] || die "$PROOF has no single row for $stem"
        level=$(jq -r --arg s "$stem" '.contracts[] | select(.stem == $s) | .proof_level' "$PROOF")
        [ -n "$level" ] || die "$PROOF records no level for $stem"
        rows+=$(printf '| [%s](examples/%s.rs) | [`%s`](https://github.com/mdipierro/nlib/blob/%s/%s#L%s) | [%s](contracts/%s.yaml) · [shape](contracts/shapes.ttl#L%s) | [%s](%s#L%s) | `cargo run --example %s` | %s |' \
            "$ex" "$ex" "$sym" "$ref" "$file" "$line" "$stem" "$stem" "$shape_l" "$level" "$PROOF" "$proof_l" "$ex" "$what")
        rows+=$'\n'
        N_EX=$((N_EX + 1))
    done < <(grep -v '^#' "$origins")
    nonzero examples "$N_EX"
    local n_rs
    n_rs=$(find examples -maxdepth 1 -name '*.rs' | grep -c . || true)
    [ "$n_rs" = "$N_EX" ] || die "$origins names $N_EX example(s), examples/ holds $n_rs"
    EXAMPLE_TEXT=$(
        printf '| Example | Python original (nlib @ `%s`) | Contract · SHACL shape | Proof | Run | What it does |\n' "${ref:0:7}"
        printf '|---------|-----------------|------------------------|-------|-----|--------------|\n'
        printf '%s' "$rows"
    )
}

# The proof summary: every number is a field of the committed receipt contracts/proof-status.json.
measure_proofs() {
    local schemas
    schemas=$(grep -lxF '  kind: schema' contracts/*.yaml | sed 's|^contracts/||; s|\.yaml$||' || true)
    PROOF_TEXT=$(jq -r --arg schemas "$schemas" '
        def rank: ltrimstr("L") | tonumber;
        .totals as $t
        | ($schemas | split("\n") | map(select(. != ""))) as $sch
        | [.contracts[] | select(.stem as $s | $sch | index($s) | not)] as $kern
        | [.contracts[] | select(.stem as $s | $sch | index($s))] as $sc
        | [$kern[] | select(.obligations > 0)] as $k
        | [$kern[] | select(.obligations == 0) | "`\(.stem)` (\(.proof_level))"] as $none
        | ([$k[].proof_level] | min_by(rank)) as $min
        | ([$k[] | select(.proof_level == $min)] | length) as $at_min
        | (["tested"] + (if $t.kani_harnesses > 0 then ["Kani model-checked"] else [] end)
                      + (if $t.lean_grounded > 0 then ["Lean-proved"] else [] end)
          | join(" + ")) as $how
        | "**`pv proof-status` level: \($min) (\($how)), \($t.bindings_implemented)/\($t.bindings_total) bindings verified.**",
          "",
          "| Measure (`pv proof-status --verify-bindings`) | Value |",
          "|--------|-------|",
          "| Contracts | \($t.contracts): \($k | length) with proof obligations (\($at_min) at \($min), the lowest level)\(if ($sc | length) > 0 then "; \($sc | length) schema contract(s) over data, not code: \([$sc[] | "`\(.stem)` (\(.proof_level))"] | join(", "))" else "" end)\(if ($none | length) > 0 then "; \($none | length) with none, which pv reports at L1: \($none | join(", "))" else "" end) |",
          "| Levels | \([.contracts[].proof_level] | group_by(.) | map("\(.[0]): \(length)") | join(", ")) |",
          "| Proof obligations | \($t.obligations) (\($t.not_applicable) N/A) |",
          "| Falsification tests | \($t.falsification_tests) |",
          "| Kani harnesses | \($t.kani_harnesses) |",
          "| Lean theorems proved (grounded in an equation) | \($t.lean_proved) (\($t.lean_grounded)) |",
          "| Bindings verified in source | \($t.bindings_implemented)/\($t.bindings_total) |"
        ' "$PROOF" 2>/dev/null) || die "$PROOF is not a pv proof-status receipt"
    [ -n "$PROOF_TEXT" ] || die "$PROOF holds no contracts"

    # pv counts a declared Kani harness without looking for it; say how many exist.
    local kt stale
    kt=$(bash scripts/proof_ratchet.sh --kani-table) || die "proof_ratchet.sh --kani-table failed"
    n_k=$(printf '%s\n' "$kt" | grep -c . || true)
    nonzero "contracts declaring Kani harnesses" "$n_k"
    backed=$(awk -F'\t' '$2 == $3' <<<"$kt" | grep -c . || true)
    phantom=$(awk -F'\t' '{ s += $2 - $3 } END { print s + 0 }' <<<"$kt")
    stale=$(awk -F'\t' '$2 != $3 { printf "%s%s (%s of %s)", sep, $1, $3, $2; sep = ", " }' <<<"$kt")
    PROOF_TEXT+=$'\n'"| Contracts whose every declared Kani harness exists in \`src/\` | $backed of $n_k |"
    PROOF_TEXT+=$'\n'"| Declared Kani harnesses with no \`#[kani::proof]\` function (phantom) | $phantom |"
    if [ "$phantom" -gt 0 ]; then
        PROOF_TEXT=${PROOF_TEXT/'.**'/"; the Kani harnesses exist for $backed of the $n_k contracts that declare them.**"}
        PROOF_TEXT+=$'\n\n'"pv counts a declared \`harness:\` toward L3 without checking that it exists, so L3 is"
        PROOF_TEXT+=$'\n'"backed by a real Kani proof only for the $backed contracts above. These contracts name"
        PROOF_TEXT+=$'\n'"harnesses that are missing (present of declared): $stale."
        PROOF_TEXT+=$'\n'"\`scripts/proof_ratchet.sh\` fails the gate if the phantom count rises."
    fi
}

# measure_enforcement — the counts in "What is enforced, and what is not". Each comes from the file
# that enforces it: the gate's needs from ci.yml (scripts/ci_gate.sh), the gate steps from
# contracts_gate.sh, the macros from build.rs, the Kani bounds from src/kani_harnesses.rs, the
# phantom baseline from contracts/proof-baseline.json, the mutant backlog from the conformance doc.
measure_enforcement() {
    cd "$REPO_ROOT" || exit 3
    REQUIRED=$(bash scripts/ci_gate.sh --required | awk -F'\t' '{ printf "%s`%s`", sep, $2; sep = ", " }') \
        || die "scripts/ci_gate.sh --required failed"
    [ -n "$REQUIRED" ] || die "the gate job needs no job"
    N_REQUIRED=$(bash scripts/ci_gate.sh --required | grep -c .)
    ADVISORY=$(bash scripts/ci_gate.sh --advisory | awk -F'\t' '{ printf "%s`%s`", sep, $2; sep = ", " }')
    [ -n "$ADVISORY" ] || ADVISORY=none
    GATE_STEPS=$(sed -n 's/^STEPS=(\(.*\))$/\1/p' scripts/contracts_gate.sh | wc -w)
    MACROS=$(grep -c 'macro_rules!' build.rs || true)
    MACRO_CALLS=$(grep -rhoE 'contract_(pre|post)_[a-z_]+!' src | grep -c . || true)
    UNWIND_MIN=$(grep -oE 'kani::unwind\([0-9]+\)' src/kani_harnesses.rs | tr -dc '0-9\n' | sort -n | head -1)
    UNWIND_MAX=$(grep -oE 'kani::unwind\([0-9]+\)' src/kani_harnesses.rs | tr -dc '0-9\n' | sort -n | tail -1)
    GOLDEN=$(grep -c '#\[test\]' tests/golden_vectors.rs || true)
    MISSED=$(grep -oE 'had [0-9]+ missed mutants' docs/ontology-conformance.md | grep -oE '[0-9]+' | head -1)
    PH_BASE=$(jq -r '.phantom_kani_harnesses' contracts/proof-baseline.json)
    LEVELS=$(jq -r '[.contracts[].proof_level] | group_by(.) | map("\(length) at \(.[0])") | join(", ")' "$PROOF")
    LEAN=$(jq -r '.totals.lean_grounded' "$PROOF")
    nonzero "gate needs" "$N_REQUIRED"
    nonzero "contracts gate steps" "$GATE_STEPS"
    nonzero "contract macros" "$MACROS"
    nonzero "contract macro call sites" "$MACRO_CALLS"
    nonzero "Kani unwind bound" "$UNWIND_MAX"
    nonzero "golden vector tests" "$GOLDEN"
    nonzero "missed-mutant backlog" "$MISSED"
    case "$PH_BASE" in '' | *[!0-9]*) die "contracts/proof-baseline.json records no phantom_kani_harnesses" ;; esac
    case "$LEAN" in '' | *[!0-9]*) die "$PROOF records no lean_grounded" ;; esac
}

# render_claims — the claim entities, contracts/enforcement-claims.src.json with every {{NAME}}
# replaced by its measured value, as the canonical JSON that evidence/enforcement/claims.json must
# equal. contracts/enforcement-claims-v1.yaml closes these entities with a SHACL shape, which
# `pv lint --gate shapes` checks on the committed file.
render_claims() {
    local vars out left
    vars=$(jq -n --arg N_REQUIRED "$N_REQUIRED" --arg REQUIRED "$REQUIRED" --arg SHAPES "$SHAPES" \
        --arg FOCUS "$FOCUS" --arg N_EX "$N_EX" --arg GATE_STEPS "$GATE_STEPS" --arg PH_BASE "$PH_BASE" \
        --arg LEVELS "$LEVELS" --arg KANI "$KANI" --arg UNWIND_MIN "$UNWIND_MIN" --arg UNWIND_MAX "$UNWIND_MAX" \
        --arg UNWIND_LOOPS "$((UNWIND_MAX - 1))" --arg KANI_BACKED "$backed" --arg KANI_CONTRACTS "$n_k" \
        --arg PHANTOM "$phantom" --arg MACROS "$MACROS" --arg MACRO_CALLS "$MACRO_CALLS" --arg GOLDEN "$GOLDEN" \
        --arg LEAN "$LEAN" --arg MISSED "$MISSED" '$ARGS.named')
    out=$(jq --argjson v "$vars" 'walk(if type == "string"
            then reduce ($v | to_entries[]) as $e (.; gsub("\\{\\{" + $e.key + "\\}\\}"; $e.value))
            else . end)' "$CLAIMS_SRC") || die "$CLAIMS_SRC is not JSON"
    left=$( (grep -oE '\{\{[A-Za-z_]*\}\}' <<<"$out" || true) | sort -u | tr '\n' ' ')
    [ -z "$left" ] || die "$CLAIMS_SRC names a value nothing measures: $left"
    printf '%s\n' "$out"
}

# check_claims <claims.json> — what the shape cannot see: each claim's job against the workflow. An
# enforced or unplanted claim must name `gate` or a job `gate` needs; a not-enforced claim must name
# `none` or an advisory job, never one `gate` needs. Ids are unique.
check_claims() {
    local req adv bad
    req=$(bash scripts/ci_gate.sh --required | cut -f1) || die "scripts/ci_gate.sh --required failed"
    adv=$(bash scripts/ci_gate.sh --advisory | cut -f1)
    bad=$(jq -r --arg req "$req" --arg adv "$adv" '
        ($req | split("\n") + ["gate"]) as $r | ($adv | split("\n") + ["none"]) as $a
        | ((.enforced + .unplanted)[] | select(.job as $j | $r | index($j) | not)
            | "\(.id) is presented as blocking the merge, but `gate` does not need job \(.job)"),
          (.not_enforced[] | select(.job as $j | $a | index($j) | not)
            | "\(.id) is presented as not enforced, but job \(.job) is not advisory"),
          ([(.enforced + .unplanted + .not_enforced)[].id] | group_by(.)[] | select(length > 1)
            | "claim id \(.[0]) is used \(length) times")' "$1") || die "$1 is not the claims JSON"
    [ -z "$bad" ] || die "$(printf '%s; ' "$bad")"
}

# render_enforcement <claims.json> — the README section, every row a claim entity.
render_enforcement() {
    printf 'GitHub enforces only what the org ruleset "Green Main" requires, and it requires one check: `gate`.\n'
    printf 'That job runs last, and it fails unless each of these %s jobs succeeded: %s.\n' "$N_REQUIRED" "$REQUIRED"
    printf 'Advisory, never blocking: %s, and the full mutation sweep on `main`.\n' "$ADVISORY"
    printf '`scripts/ci_gate.sh --check-workflow` fails if a new job is neither needed by `gate` nor marked advisory.\n\n'
    printf 'Each row is a claim entity in [`evidence/enforcement/claims.json`](evidence/enforcement/claims.json), closed by the SHACL shape in [`contracts/enforcement-claims-v1.yaml`](contracts/enforcement-claims-v1.yaml).\n'
    jq -r '
        "\(.enforced | length) claims are enforced and proved by a plant; \(if (.unplanted | length) > 0 then "\(.unplanted | length) block the merge but no plant has proved them yet; " else "" end)\(.not_enforced | length) are not enforced.",
        "",
        "| Claim | Mechanism | What turns it RED | Blocks merge | Plant receipt | Honest limit |",
        "|-------|-----------|-------------------|--------------|---------------|--------------|",
        ((.enforced[] | . + {status: "yes", receipt: "\(.plant) ([job](\(.plant_run)))"}),
         (.unplanted[] | . + {status: "yes", receipt: "**none yet**: not proved by a plant"}),
         (.not_enforced[] | . + {status: "no", receipt: "-"})
        | "| \(.claim) | \(.mechanism) | \(.red_when) | \(.status) | \(.receipt) | \(.limit) |")' "$1"
    printf '\n**A claim counts only if a planted fault turns a REQUIRED check red, and here the only required check is `gate`.** Everything else in this README is a measurement, not a guarantee.\n'
}

render_table() {
    printf '%s\n\n' "$TABLE_TEXT"
    printf '**%s contracts, %s equations; mean contract score %s (%s); codebase grade %s (%s).**\n' \
        "$N_CONTRACTS" "$N_EQ" "$MEAN" "$MEAN_GRADE" "$CB_GRADE" "$CB_SCORE"
}

render_metrics() {
    printf '| Metric | Value |\n'
    printf '|--------|-------|\n'
    printf '| Contracts | %s |\n' "$N_CONTRACTS"
    printf '| Equations | %s |\n' "$N_EQ"
    printf '| Bound symbols (extract:code) | %s resolved, %s unresolved |\n' "$RESOLVED" "$UNRESOLVED"
    printf '| SHACL shapes | %s, over %s focus nodes |\n' "$SHAPES" "$FOCUS"
    printf '| Kani BMC harnesses | %s |\n' "$KANI"
    printf '| Contract grade | %s (%s mean) |\n' "$MEAN_GRADE" "$MEAN"
    printf '| Codebase grade | %s (%s) |\n' "$CB_GRADE" "$CB_SCORE"
    printf '| External deps | 1 (aprender only) |\n'
}

# replace_block <file> <name> <body-file>: the lines between the markers become the body.
replace_block() {
    local start="<!-- $2_START -->" end="<!-- $2_END -->"
    [ "$(grep -cxF "$start" "$1")" = 1 ] && [ "$(grep -cxF "$end" "$1")" = 1 ] \
        || die "README carries no single $2 marker pair" 3
    awk -v s="$start" -v e="$end" -v body="$3" '
        $0 == s { print; while ((getline line < body) > 0) print line; skip = 1; next }
        $0 == e { skip = 0 }
        !skip' "$1"
}

render_shapes() {
    printf '| What `pv lint contracts/ --gate shapes` measured | Value |\n'
    printf '|--------|-------|\n'
    printf '| SHACL shapes (one per example contract) | %s |\n' "$SHAPES"
    printf '| Focus nodes (example `--json` receipts in `evidence/examples/`) | %s |\n' "$FOCUS"
    printf '| RDF triples checked | %s |\n' "$TRIPLES"
    printf '| Violations | 0 (any violation is exit 1) |\n'
    printf '| Planted control: pv'"'"'s own broken receipt must violate | %s, %s violations |\n' "$PC_SHAPE" "$PLANT_V"
    printf '| Extractor controls fired | %s of %s |\n' "$PC_FIRED" "$PC_N"
    printf '| W3C SHACL conformance cases | %s of %s |\n' "$W3C" "$W3C_N"
    printf '| Bound symbols resolved in source | %s (%s unresolved) |\n' "$RESOLVED" "$UNRESOLVED"
}

# rendered_readme <claims.json> <out>: the header line, then the template with every generated block
# filled. Nothing is copied from README.md itself, so every README byte is generated.
rendered_readme() {
    local cur nxt body name
    cur="$(mktemp)"
    nxt="$(mktemp)"
    body="$(mktemp)"
    grep -qF 'GENERATED by scripts/readme_sync.sh' "$TEMPLATE" && die "$TEMPLATE carries the generated header; only README.md does" 3
    { printf '%s\n' "$GENERATED_HEADER"; cat "$TEMPLATE"; } >"$cur"
    for name in ENFORCEMENT CONTRACT_TABLE SHACL_SUMMARY PROOF_STATUS EXAMPLE_TABLE CONTRACT_METRICS; do
        {
            printf '\n'
            case "$name" in
                ENFORCEMENT) render_enforcement "$1" ;;
                CONTRACT_TABLE) render_table ;;
                SHACL_SUMMARY) render_shapes ;;
                PROOF_STATUS) printf '%s\n' "$PROOF_TEXT" ;;
                EXAMPLE_TABLE) printf '%s\n' "$EXAMPLE_TEXT" ;;
                CONTRACT_METRICS) render_metrics ;;
            esac
            printf '\n'
        } >"$body"
        replace_block "$cur" "$name" "$body" >"$nxt"
        cp "$nxt" "$cur"
    done
    cp "$cur" "$2"
    rm -f "$cur" "$nxt" "$body"
}

# same <generated> <committed> <what>: 0 iff the bytes are equal; else print the diff.
# self_test — every claim fault the gate promises to catch, planted in a scratch copy of the repo and
# checked with the real instruments: pv's shapes gate on the claim entities, check_claims on each
# claim's job, and --check on a README with one byte edited. The unedited copy is the control.
self_test() {
    local d pass=0 fail=0
    d=$(mktemp -d)
    (cd "$REPO_ROOT" && cp -r contracts evidence src build.rs Cargo.toml Cargo.lock README.md "$d/") \
        || die "cannot copy the repo into $d"
    rm -rf "${d:?}/contracts/.pv"
    cp "$d/evidence/enforcement/claims.json" "$d/claims.good"
    row() { # row <message> <0|1 got> <0|1 want>
        if [ "$2" = "$3" ]; then
            pass=$((pass + 1))
            printf 'ok   %s\n' "$1"
        else
            fail=$((fail + 1))
            printf 'FAIL %s\n' "$1"
        fi
    }
    shape() { # shape <want 0|1> <message> <jq edit>: the edit to claims.json, then pv's shapes gate
        local got=0
        jq "$3" "$d/claims.good" >"$d/evidence/enforcement/claims.json"
        (cd "$d" && "$PV" lint contracts/ --gate shapes --format json >"$d/out.json" 2>/dev/null) || got=1
        # A rejection must be the claims shape rejecting, not some other entity.
        if [ "$got" = 1 ] && ! jq -e '[.findings[]? | select(.rule_id == "PV-ONT-011")
                | select(.message | contains("enforcement-claims-v1"))] | length > 0' "$d/out.json" >/dev/null; then
            got=2
        fi
        row "$2" "$got" "$1"
    }
    claims() { # claims <want 0|1> <message> <jq edit>: the edit, then check_claims
        local got=0
        jq "$3" "$d/claims.good" >"$d/edited.json"
        (cd "$REPO_ROOT" && check_claims "$d/edited.json") >/dev/null 2>&1 || got=1
        row "$2" "$got" "$1"
    }
    shape 0 "the committed claims conform to their shape (control)" '.'
    shape 1 "an enforced claim with no plant run violates the shape" '.enforced[0].plant_run = "none"'
    shape 1 "an enforced claim whose plant run is not a CI job URL violates the shape" \
        '.enforced[0].plant_run = "https://github.com/paiml/rust-mdipierro-nlib/actions/runs/1"'
    shape 1 "an advisory job presented as enforced violates the shape" '.enforced[0].job = "comply"'
    shape 1 "a not-enforced claim that says it blocks the merge violates the shape" \
        '.not_enforced[0].blocks_merge = true'
    shape 1 "a claim outside the enforced class that cites a plant run violates the shape" \
        '(.unplanted // [] | length) as $n | if $n > 0 then .unplanted[0].plant_run = .enforced[0].plant_run else .not_enforced[0].plant_run = .enforced[0].plant_run end'
    shape 1 "a claim with no honest limit violates the shape" 'del(.enforced[0].limit)'
    shape 1 "a claim with a key the shape does not close over violates it" '.enforced[0].note = "x"'
    shape 1 "a claim id outside CLAIM-NNN violates the shape" '.enforced[0].id = "C-1"'
    claims 0 "the committed claims name jobs the workflow agrees with (control)" '.'
    claims 1 "a blocking claim on a job the gate does not need is refused" '.enforced[0].job = "comply"'
    claims 1 "a not-enforced claim on a job the gate needs is refused" '.not_enforced[0].job = "kani"'
    claims 1 "two claims with one id are refused" '.not_enforced[0].id = .enforced[0].id'
    cp "$REPO_ROOT/README.md" "$d/README.md"
    local got=0
    README_PATH="$d/README.md" bash "$REPO_ROOT/scripts/readme_sync.sh" --check >/dev/null 2>&1 || got=1
    row "the committed README.md is what the generator produces (control)" "$got" 0
    sed -i '2s/^./X/' "$d/README.md"
    got=0
    README_PATH="$d/README.md" bash "$REPO_ROOT/scripts/readme_sync.sh" --check >/dev/null 2>&1 || got=1
    row "one hand-edited README byte fails --check" "$got" 1
    rm -rf "${d:?}"
    printf 'readme_sync: self-test: %d passed, %d failed\n' "$pass" "$fail"
    [ "$fail" -eq 0 ]
}

same() {
    cmp -s "$1" "$2" && return 0
    printf 'readme_sync: %s differs from what the generator produces:\n' "$3" >&2
    diff -u "$2" "$1" >&2 || true
    return 1
}

mode="${1:---write}"
case "$mode" in
    --write | --print | --check) ;;
    --self-test)
        self_test
        exit
        ;;
    *) usage ;;
esac
[ -f "$TEMPLATE" ] || die "no README template at $TEMPLATE" 3
[ -f "$CLAIMS_SRC" ] || die "no enforcement claims at $CLAIMS_SRC" 3
measure
claims="$(mktemp)"
readme="$(mktemp)"
trap 'rm -f "$claims" "$readme"' EXIT
render_claims >"$claims"
check_claims "$claims"
rendered_readme "$claims" "$readme"

case "$mode" in
    --print)
        cat "$claims" "$readme"
        ;;
    --write)
        mkdir -p "$(dirname "$CLAIMS")"
        cp "$claims" "$CLAIMS"
        cp "$readme" "$README"
        printf 'readme_sync: wrote %s and README.md (%s contracts, %s equations)\n' "${CLAIMS#"$REPO_ROOT"/}" "$N_CONTRACTS" "$N_EQ"
        ;;
    --check)
        rc=0
        [ -f "$CLAIMS" ] || die "no claims at $CLAIMS; run: bash scripts/readme_sync.sh --write"
        [ -f "$README" ] || die "no README at $README; run: bash scripts/readme_sync.sh --write"
        same "$claims" "$CLAIMS" "${CLAIMS#"$REPO_ROOT"/}" || rc=1
        same "$readme" "$README" README.md || rc=1
        [ "$rc" = 0 ] || die "a generated file is stale or was edited by hand; run: bash scripts/readme_sync.sh --write"
        printf 'readme_sync: README.md and %s in sync (%s contracts, %s equations)\n' "${CLAIMS#"$REPO_ROOT"/}" "$N_CONTRACTS" "$N_EQ"
        ;;
esac
